addr: ":80"
profile: false
pprof_addr: ":6061"
jwt_secret: "some_Secret_key_123"
server:
  readTimeout: 5
  writeTimeout: 10
  idleTimeout: 10
db:
  host: "localhost"
  port:     5432,
  user:     "app",
  password: "app",
  name:   "app",
  sslMode:  "disable",
modules:
  - "users"
  - "booking"
  - "scheduling"
origins:
  - "http://localhost"
  - "http://*.localhost"
